version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
    container_name: goapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MONGO_URL: mongodb://mongodb:27017

volumes:
  mongo-data:
